<?php
/**
 * @copyright Limbas GmbH <https://limbas.com>
 * @license https://opensource.org/licenses/GPL-2.0 GPL-2.0
 *
 * This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 */



# LMB_DBTYPE #
const LMB_DBTYPE_CHAR = 'CHAR';
const LMB_DBTYPE_VARCHAR = 'VARCHAR';
const LMB_DBTYPE_INTEGER = 'INTEGER';
const LMB_DBTYPE_SMALLINT = 'SMALLINT';
const LMB_DBTYPE_BIGINT = 'BIGINT';
const LMB_DBTYPE_FLOAT = 'FLOAT';
const LMB_DBTYPE_FIXED = 'FIXED';
const LMB_DBTYPE_NUMERIC = 'NUMERIC';
const LMB_DBTYPE_BOOLEAN = 'BOOLEAN';
const LMB_DBTYPE_DATE = 'DATE';
const LMB_DBTYPE_TIME = 'TIME';
const LMB_DBTYPE_TIMESTAMP = 'TIMESTAMP';
const LMB_DBTYPE_LONG = 'LONG';
const LMB_DBTYPE_ASCII = 'ASCII';
const LMB_DBTYPE_BYTE = 'BYTE';
const LMB_DBTYPE_SERIAL = 'SERIAL';

# LMB_DBDEF #
const LMB_DBDEF_TIME = 'TIME';
const LMB_DBDEF_DATE = 'DATE';
const LMB_DBDEF_TIMESTAMP = 'TIMESTAMP';
const LMB_DBDEF_FALSE = 'FALSE';
const LMB_DBDEF_TRUE = 'TRUE';
const LMB_DBDEF_NULL = 'NULL';
const LMB_DBDEF_DTNULL = 'NULL';

# LMB_DBRETYPE #
const LMB_DBRETYPE_CHAR = 'CHAR';
const LMB_DBRETYPE_VARCHAR = 'VARCHAR';
const LMB_DBRETYPE_INTEGER = 'INTEGER';
const LMB_DBRETYPE_SMALLINT = 'SMALLINT';
const LMB_DBRETYPE_FLOAT = 'FLOAT';
const LMB_DBRETYPE_FIXED = 'FIXED';
const LMB_DBRETYPE_NUMERIC = 'NUMERIC';
const LMB_DBRETYPE_BOOLEAN = 'BOOLEAN';
const LMB_DBRETYPE_DATE = 'DATE';
const LMB_DBRETYPE_TIME = 'TIME';
const LMB_DBRETYPE_TIMESTAMP = 'TIMESTAMP';
const LMB_DBRETYPE_LONG = 'LONG';
const LMB_DBRETYPE_CLOB = 'LONG';

# LMB_DBREDEF #
const LMB_DBREDEF_TIMESTAMP = 'TIMESTAMP';
const LMB_DBREDEF_DEFAULT_TIMESTAMP = 'TIMESTAMP';
const LMB_DBREDEF_DEFAULT_DATE = 'DATE';
const LMB_DBREDEF_FALSE = 'FALSE';
const LMB_DBREDEF_TRUE = 'TRUE';

# LMB_DBFUNC #
const LMB_DBFUNC_ISNULL = 'IS NULL';
const LMB_DBFUNC_PRIMARY_KEY = 'PRIMARY KEY';
const LMB_DBFUNC_UNIQUE = 'UNIQUE';
const LMB_DBFUNC_CONCAT = '&';
const LMB_DBFUNC_UMASCB = '\\';
#const LMB_DBFUNC_LIMIT = 'LIMIT';
const LMB_DBFUNC_ROWNO = 'ROWNO';
const LMB_DBFUNC_SPLIT_TRIGGER = 'EXECUTE';
const LMB_DBFUNC_ADD_COLUMN_FIRST = 'ADD';
const LMB_DBFUNC_ADD_COLUMN_NEXT = '';
const LMB_DBFUNC_DROP_COLUMN_FIRST = 'DROP';
const LMB_DBFUNC_DROP_COLUMN_NEXT = '';
const LMB_DBFUNC_DATE = 'DATE(';
const LMB_DBFUNC_TIME = 'TIME(';
const LMB_DBFUNC_YEAR = 'YEAR(';
const LMB_DBFUNC_MONTH = 'MONTH(';
const LMB_DBFUNC_DAY = 'DAY(';
const LMB_DBFUNC_HOUR = 'HOUR(';
const LMB_DBFUNC_MINUTE = 'MINUTE(';

const LMB_DBFUNC_LONGHANDLE = 0;
const LMB_DBFUNC_PROCEDUREHANDLE = 1;
const LMB_DBFUNC_FKEYHANDLE = 1;
const LMB_DBFUNC_FLOATHANDLE = 1;
const LMB_DBFUNC_PREPAREHANDLE = 1;
const LMB_DBFUNC_TIMEHANDLE = 1;
const LMB_DBFUNC_NUMROWS = 1;
const LMB_DBFUNC_SEQUENCE = 1;
const LMB_DBFUNC_VIEWGALIAS = 0;
const LMB_DBFUNC_VIEWDEPENDENCY = 0;
const LMB_DBFUNC_MAXFIELDNAMESIZE = 30;
const LMB_DBFUNC_MAXTABLENAMESIZE = 30;
const LMB_DBFUNC_TRANSACTION = 1;
const LMB_DBFUNC_TRANSACTION_WITH_SCHEMA = 1;

# DBCURSOR #
const LMB_DBCURSOR = 1;
const LMB_DBFUNC_WITH_RECURSIVE = 'DECLARE C CURSOR FOR WITH RECURSIVE';
